/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IFa6SolidArrowLeft: typeof import('~icons/fa6-solid/arrow-left')['default']
    IFa6SolidArrowRight: typeof import('~icons/fa6-solid/arrow-right')['default']
    IFa6SolidCode: typeof import('~icons/fa6-solid/code')['default']
    IFa6SolidXmark: typeof import('~icons/fa6-solid/xmark')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
